<div class="container-fluid">
    <div class="row no-margins">
        <div class="col-md-12 mb-3">
            <?php include('ads/rectangle-ad.php');?>
        </div>
        <div class="col-md-12">
            <h2 class="mb-3">WHAT IS CONVERT TO PNG?</h2>
            <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent pellentesque massa vitae laoreet commodo. Integer quis feugiat est, quis tempus sem. Suspendisse interdum sit amet nulla quis hendrerit. Proin dapibus turpis sed dui pulvinar euismod. Aenean semper, nisl vitae finibus sodales, eros lacus rutrum nisl, nec varius mauris est nec nisl. Vivamus luctus massa at nisl molestie lacinia at id mauris. Quisque congue ligula vel nunc auctor tempus eu nec lacus. Aliquam tincidunt pellentesque condimentum. Nam et massa lobortis urna rutrum egestas. Nulla mattis interdum rutrum. Aenean sollicitudin massa et orci sagittis cursus in vitae augue.</p>
            <p class="text-justify">Cras maximus tincidunt magna, sit amet tempor arcu maximus vel. Proin cursus congue lacus, sed malesuada urna placerat eget. Duis hendrerit velit velit, eget pellentesque turpis pulvinar non. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam tempor ante lectus, in lacinia purus imperdiet nec. Pellentesque non mi sed risus hendrerit ullamcorper in nec lacus. Pellentesque eleifend ultrices leo vitae vehicula. Donec quis pulvinar ex, ac interdum lacus. Donec quis risus tortor. Nulla faucibus sem lacus, quis aliquam eros ornare sed. Mauris tincidunt ex eget augue pellentesque, quis varius nunc egestas.</p>
            <h2 class="mb-3">HOW TO USE CONVERT TO PNG TOOL?</h2>
            <p class="text-justify">Proin non ex fringilla, efficitur felis posuere, pretium dolor. Nulla vehicula pharetra tristique. Praesent venenatis lacinia dui quis vehicula. Fusce in lobortis augue, vel ornare ex. Donec ultrices rhoncus magna, nec venenatis massa pretium at. Nullam efficitur dictum tellus, vel vulputate nulla suscipit in. Sed sed malesuada urna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec erat est, mollis vel pulvinar ut, volutpat sed mauris. Proin semper nibh vel imperdiet varius.</p>
            <p class="text-justify">Donec nisi erat, hendrerit et dictum ac, ornare vel massa. Sed leo dui, finibus id venenatis non, varius vel metus. Suspendisse vulputate odio at mauris porta sodales. Mauris lobortis risus non nibh finibus fringilla. Suspendisse tristique in ligula et eleifend. Phasellus congue est ac turpis pharetra, vitae feugiat eros laoreet. Mauris velit nisl, aliquet id augue non, rhoncus elementum purus. Duis vel molestie nibh. Fusce fermentum mollis arcu sit amet commodo. Proin ac fringilla quam. Quisque mattis neque in risus scelerisque consequat. Nunc lacinia tellus nec vestibulum ornare.</p>
            <p class="text-justify">Nullam erat leo, euismod non quam in, sagittis laoreet lorem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi posuere enim libero, eu sollicitudin turpis gravida non. Quisque cursus congue vehicula. Donec sed risus leo. Maecenas maximus tristique odio eu tincidunt. Praesent ullamcorper sem tincidunt augue molestie, eu condimentum sem scelerisque. Nulla arcu tellus, rutrum eget convallis a, hendrerit sed neque. Curabitur felis eros, mollis non eros et, posuere rhoncus elit. Praesent arcu quam, egestas a fringilla a, mollis sed ipsum. Nam eleifend, ipsum eget mollis convallis, diam neque efficitur nunc, a commodo turpis libero a lacus. Sed vel leo ligula.</p>
        </div>
    </div>
</div>